CADC-11904: add debugging log msgs to TokenTool
opencadc/ac pull request #132
Opened 2022-10-13 20:21 UTC by hjeeves

So debugging issues with tokens will be easier in future.

2022-10-13 21:28 UTC, brianmajor requested changes
version should probably just be 0.3.4 instead of 0.4.  otherwise looking good.

2022-10-14 15:34 UTC, pdowler commented on cadc-permissions/src/main/java/org/opencadc/permissions/TokenTool.java
> +        log.debug("[TokenTool.validateToken]: uri: " + uri);
Having to put the TokenTool class name here is a sign of our generally poor logging config, where we only log the message (info level start and end messages are json) so we lose out on all the stuff log4j does for us :-(

and to top it off, the json makes logs unreadable and we don't ingest them into something that can search anyway :-( :-(

2022-10-14 15:36 UTC, pdowler commented on cadc-permissions/src/main/java/org/opencadc/permissions/TokenTool.java
> +        log.debug("[TokenTool.validateToken]: uri: " + uri);
This could have also been fixed more widely by fixing the Log4jInit to use a proper log format for debug messages

2022-10-14 15:36 UTC, pdowler approved these changes

2022-10-14 15:37 UTC, merged